//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by JPEGsnoop.rc
//
#define IDS_CAL_EXE_OPEN                1
#define IDR_CNTR_INPLACE                6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_FAILED_TO_CREATE            102
#define IDD_SETTINGSDLG                 103
#define IDD_TERMSDLG                    104
#define IDD_UPDATEAVAILDLG              105
#define IDD_MODELESSDLG                 106
#define IDD_NOTEDLG                     107
#define IDD_DBMANAGEDLG                 109
#define IDD_EXPORTDLG                   112
#define IDD_DECODEDETAILDLG             113
#define IDD_EXPORTTIFFDLG               116
#define IDR_MAINFRAME                   128
#define IDR_JPEGsnoopTYPE               129
#define IDR_MAINFRAME_BAK               129
#define IDD_DBSUBMITDLG                 130
#define IDR_TEST1TYPE                   130
#define IDD_OVERLAYBUFDLG               131
#define IDR_TEST2TYPE                   131
#define IDD_LOOKUP                      132
#define IDR_MAINFRAME2                  132
#define IDD_OFFSETDLG                   133
#define IDR_MAINFRAME3                  133
#define IDR_MAINFRAME_AVI               134
#define IDR_MAINFRAME_ALL               135
#define ID_INDICATOR_YCC                136
#define IDS_CAL_FILEOPEN                137
#define IDS_CAL_FILESAVE                138
#define ID_INDICATOR_MCU                139
#define ID_INDICATOR_FILEPOS            140
#define IDC_DB_DIR                      1000
#define IDC_URL                         1001
#define IDC_DB_DIR_BROWSE               1001
#define IDC_URL_DOC                     1002
#define IDC_UPDATE_CHK                  1002
#define IDC_VER_NUM                     1003
#define IDC_DB_DIR_DEFAULT              1003
#define IDC_EULA                        1004
#define IDC_EULA_OK                     1005
#define IDC_UPDATE_AUTO                 1006
#define IDC_BASEH                       1007
#define IDC_BUTTON1                     1007
#define IDC_BASED                       1008
#define IDC_VER_CUR                     1008
#define IDC_OFFSETVAL                   1009
#define IDC_VER_LATEST                  1009
#define IDC_X                           1010
#define IDC_UPDATE_AUTO_STILL           1010
#define IDC_Y                           1011
#define IDC_OFFSET                      1012
#define IDC_DATE_LATEST                 1012
#define IDC_BTN_CALC                    1013
#define IDC_COACH_OFF                   1013
#define IDC_RNGX                        1014
#define IDC_MSG                         1014
#define IDC_RNGY                        1015
#define IDC_COACH_RESET                 1015
#define IDC_REPROCESS_AUTO              1016
#define IDC_UPDATE_CHK_DAYS             1017
#define IDC_OVRPOS                      1018
#define IDC_OVRNEW                      1019
#define IDC_OVRCUR                      1020
#define IDC_LIST                        1020
#define IDC_OVR_LOAD                    1021
#define IDC_REMOVEALL                   1022
#define IDC_OVRCURBIN                   1022
#define IDC_OVRLEN                      1023
#define IDC_REMOVE                      1023
#define IDC_OVREN                       1024
#define IDC_QUAL                        1025
#define IDC_DBSUBMIT_NET                1025
#define IDC_MAKE                        1026
#define IDC_MODEL                       1027
#define IDC_SIG                         1028
#define IDC_RPTERRMAX_SCANDECODE        1028
#define IDC_SOFTWARE                    1029
#define IDC_APPLY                       1029
#define IDC_RADIO_CAM                   1031
#define IDC_RADIO_SW                    1032
#define IDC_USER_SOFTWARE               1033
#define IDC_RADIO_UNKNOWN               1035
#define IDC_NOTES                       1036
#define IDC_OVERLAY                     1052
#define IDC_DHTAVI                      1053
#define IDC_OFFSET_START                1054
#define IDC_EDIT1                       1071
#define IDC_EDIT2                       1072
#define IDC_EDIT3                       1073
#define IDC_CHECK1                      1074
#define IDC_FORCE_EOI                   1077
#define IDC_FORCE_EOI2                  1078
#define IDC_FORCE_SOI                   1078
#define IDC_IGNORE_EOI                  1081
#define IDC_BTN_LOAD                    1109
#define IDC_EDIT_FNAME                  1112
#define IDC_RAD_RGB16                   1113
#define IDC_RAD_YCC8                    1114
#define IDC_RAD_RGB8                    1115
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_TOOLS_DECODE                 32771
#define ID_FILE_OFFSET                  32772
#define ID_TOOLS_SEARCHFORWARD          32773
#define ID_TOOLS_SEARCHREVERSE          32774
#define ID_TOOLS_LOOKUPMCUOFFSET        32775
#define ID_TOOLS_FILEOVERLAY            32776
#define ID_TOOLS_DECODESCANRANGE        32777
#define ID_TOOLS_ADDCAMERATODB          32778
#define ID_TOOLS_RESETLOCALDB           32779
#define ID_OPTIONS_DHTEXPAND            32780
#define ID_OPTIONS_MAKERNOTES           32781
#define ID_OPTIONS_SCANDUMP             32782
#define ID_OPTIONS_SCANPARSE            32783
#define ID_OPTIONS_HISTOYDUMP           32784
#define ID_FILE_REPROCESS               32788
#define ID_FILE_OPENIMAGE               32789
#define ID_FILE_SAVELOG                 32790
#define ID_OPTIONS_DECODESCAN           32795
#define ID_OPTIONS_CONFIGURATION        32796
#define ID_OPTIONS_CHECKFORUPDATES      32799
#define ID_PREVIEW_RGB                  32800
#define ID_PREVIEW_YCC                  32801
#define ID_PREVIEW_R                    32802
#define ID_PREVIEW_G                    32803
#define ID_PREVIEW_B                    32804
#define ID_PREVIEW_Y                    32805
#define ID_PREVIEW_CB                   32806
#define ID_PREVIEW_CR                   32807
#define ID_PREVIEWZOOM_ZOOMIN           32808
#define ID_PREVIEWZOOM_ZOOMOUT          32809
#define ID_PREVIEWZOOM_100              32810
#define ID_PREVIEWZOOM_150              32811
#define ID_PREVIEWZOOM_200              32812
#define ID_PREVIEWZOOM_300              32813
#define ID_PREVIEWZOOM_400              32814
#define ID_PREVIEWZOOM_800              32815
#define ID_TOOLS_SEARCHEXECUTABLEFORDQT 32819
#define ID_TOOLS_MANAGELOCALDB          32820
#define ID_OPTIONS_SIGNATURESEARCH      32821
#define ID_TOOLS_EXTRACTEMBEDDEDJPEG    32822
#define ID_OPTIONS_DECODEAC             32824
#define ID_OPTIONS_SCANSEGMENT          32825
#define ID_SCANSEGMENT_DECODEIMAGE      32826
#define ID_SCANSEGMENT_FULLIDCT         32827
#define ID_SCANSEGMENT_HISTOGRAMY       32828
#define ID_SCANSEGMENT_SCANDUMP         32829
#define ID_SCANSEGMENT_DUMP             32830
#define ID_Menu                         32831
#define ID_VIEW_ZOOM                    32832
#define ID_VIEW_IMAGEZOOM               32833
#define ID_IMAGEZOOM_ZOOMIN             32834
#define ID_IMAGEZOOM_ZOOMOUT            32835
#define ID_IMAGEZOOM_12                 32836
#define ID_IMAGEZOOM_25                 32837
#define ID_IMAGEZOOM_50                 32838
#define ID_IMAGEZOOM_100                32839
#define ID_IMAGEZOOM_150                32840
#define ID_IMAGEZOOM_200                32841
#define ID_IMAGEZOOM_300                32842
#define ID_IMAGEZOOM_400                32843
#define ID_IMAGEZOOM_800                32844
#define ID_SCANSEGMENT_NOIDCT           32849
#define ID_TOOLS_LOOKUPMCUOFFSET32850   32850
#define ID_TOOLS_FILEOVERLAY32851       32851
#define ID_VIEW_OVERLAYS                32854
#define ID_OVERLAYS_MCUGRID             32855
#define ID_DEV_DELMCU2                  32858
#define ID_VIEW_ADJUST                  32859
#define ID_TOOLS_EXPORTMODIFIEDJPEG     32860
#define ID_TOOLS_DETAILEDSCANDECODE     32870
#define ID_SCANSEGMENT_DETAILEDDECODE   32871
#define ID_SCANSEGMENT_HISTOGRAM        32872
#define ID_OPTIONS_HIDEUKNOWNEXIFTAGS   32883
#define ID_TOOLS_EXPORTTIFF             32884

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32885
#define _APS_NEXT_CONTROL_VALUE         1116
#define _APS_NEXT_SYMED_VALUE           117
#endif
#endif
